"use client";
import { useEffect, useState } from "react";
type Series={id:string;no:string;title:string;eyebrow:string;text:string;theme:string;folder:string;files:string[]};
const series:Series[]=[
{id:"concepts",no:"01",title:"Selected Concepts",eyebrow:"Campaign · Editorial · Production",text:"Six complete visual systems spanning admissions, social media, luxury editorial, cultural events, packaging and print production.",theme:"acid",folder:"Portfolio Designs",files:["Design_04.png","Design_01.png","Design_02.png","Design_03.png","Design_05.png","Design_06.png"]},
{id:"schools",no:"02",title:"School Communication",eyebrow:"Posters · Services · Events",text:"Commercial school-facing campaigns made to explain services quickly, attract attention and convert interest into conversation.",theme:"blue",folder:"School Posters",files:["School_Poster_06.jpg","School_Poster_07.jpg","School_Poster_01.jpg","School_Poster_02.jpg","School_Poster_03.jpg","School_Poster_04.jpg","School_Poster_05.jpg"]},
{id:"social",no:"03",title:"Faith & Events",eyebrow:"Social posters · Announcements",text:"Editorial poster compositions balancing atmosphere, spiritual messaging, elegant typography and practical event information.",theme:"cream",folder:"Social Media Posters",files:["Poster_04.png","Poster_01.png","Poster_02.png","Poster_03.png","Poster_05.png"]},
{id:"local",no:"04",title:"Occasion & Local Business",eyebrow:"WhatsApp · Promotional design",text:"A diverse set of invitation, property, beauty and education creatives built for fast mobile sharing and clear response.",theme:"rose",folder:"Whatsapp Designs",files:["WhatsApp Poster (2).png","WhatsApp Poster (6).png","WhatsApp Poster (4).png","WhatsApp Poster (1).png","WhatsApp Poster (7).png","WhatsApp Poster (5).png","WhatsApp Poster (3).png","WhatsApp Poster (8).png"]},
{id:"holyspark",no:"05",title:"HolySpark Stories",eyebrow:"Vertical thumbnails · Storytelling",text:"Emotion-led vertical visuals for faith and motivation, using cinematic imagery, assertive headlines and instantly readable hooks.",theme:"black",folder:"Youtube Thumbnails",files:["Youtube_Thumbnail_ (3).png","Youtube_Thumbnail_ (4).png","Youtube_Thumbnail_ (5).png","Youtube_Thumbnail_ (2).png","Youtube_Thumbnail_ (6).png","Youtube_Thumbnail_ (1).png","Youtube_Thumbnail_ (7).png","Youtube_Thumbnail_ (8).png","Youtube_Thumbnail_ (9).png","Youtube_Thumbnail_ (10).png","Youtube_Thumbnail_ (11).png"]}
];
const pathFor=(folder:string,file:string)=>`/work/${folder.split("/").map(encodeURIComponent).join("/")}/${encodeURIComponent(file)}`;
export default function Home(){
 const[open,setOpen]=useState<{src:string;alt:string}|null>(null);const[nav,setNav]=useState(false);
 useEffect(()=>{const on=()=>setNav(scrollY>32);addEventListener("scroll",on,{passive:true});return()=>removeEventListener("scroll",on)},[]);
 useEffect(()=>{document.body.classList.toggle("locked",!!open);const esc=(e:KeyboardEvent)=>e.key==="Escape"&&setOpen(null);addEventListener("keydown",esc);return()=>removeEventListener("keydown",esc)},[open]);
 return <><header className={`nav ${nav?"navOn":""}`}><a className="logo" href="#top">AV<span>©</span></a><nav><a href="#work">Work</a><a href="#about">Profile</a><a href="#contact">Contact</a></nav></header><main id="top">
 <section className="hero"><div className="orbit orbit1"/><div className="orbit orbit2"/><div className="spark">✦</div><p className="micro">Graphic Designer · DTP Specialist · Portfolio 2026</p><h1><span>Visuals that</span><em>spark action.</em></h1><div className="heroFoot"><p>Commercial design with colour, clarity and conviction—crafted for brands, schools, events and digital audiences.</p><a href="#work">Explore 37 artworks <b>↘</b></a></div></section>
 <section className="manifesto" id="about"><p className="micro">Profile / Approach</p><div><h2>I turn everyday messages into <i>unmissable visual moments.</i></h2><p className="bodyCopy">My practice moves between high-impact campaign concepts, information-rich posters, premium event communication and cinematic digital storytelling. Every piece starts with hierarchy, emotion and the audience’s next action.</p><div className="pills"><span>Art Direction</span><span>Poster Design</span><span>Social Media</span><span>Typography</span><span>Photo Compositing</span><span>Print Production</span></div></div></section>
 <section className="marquee" aria-label="Capabilities"><div>Bold ideas • Clear hierarchy • Cultural sensitivity • Production precision • Bold ideas • Clear hierarchy • Cultural sensitivity • Production precision •</div></section>
 <div id="work">{series.map((s,si)=><section className={`projectSection ${s.theme}`} id={s.id} key={s.id}><header className="projectHead"><div className="projectNo">{s.no}</div><div><p className="micro">{s.eyebrow}</p><h2>{s.title}</h2></div><p className="projectIntro">{s.text}</p></header><div className={`gallery gallery${s.files.length}`}>{s.files.map((file,i)=>{const src=pathFor(s.folder,file);return <button className={`art art${i+1}`} key={file} onClick={()=>setOpen({src,alt:`${s.title}, artwork ${i+1}`})} aria-label={`Open ${s.title} artwork ${i+1}`}><img src={src} alt={`${s.title}, artwork ${i+1}`} loading={si===0&&i<2?"eager":"lazy"}/><span>{String(i+1).padStart(2,"0")} / {String(s.files.length).padStart(2,"0")}</span></button>})}</div></section>)}</div>
 <section className="contact" id="contact"><p className="micro">Available for full-time & freelance</p><h2>Have a brief?<br/><i>Let’s make it magnetic.</i></h2><p>Open to graphic design and DTP opportunities in India, the UAE, Saudi Arabia and remote teams worldwide.</p><div className="actions"><a href="mailto:vanzy214@gmail.com">Email me ↗</a><a href="tel:+919970760191">Call me ↗</a><a href="https://www.linkedin.com/in/avanjare214" target="_blank" rel="noopener">LinkedIn ↗</a></div><footer><span>© 2026 Ashish Vanjare</span><span>Designed with purpose. Presented with energy.</span></footer></section>
 </main>{open&&<div className="lightbox" role="dialog" aria-modal="true" onMouseDown={e=>e.currentTarget===e.target&&setOpen(null)}><button className="close" onClick={()=>setOpen(null)} aria-label="Close artwork">×</button><img src={open.src} alt={open.alt}/><p>{open.alt} · Press Esc to close</p></div>}</>
}
